apiVersion: benchops.nvidia.com/v1alpha1
kind: ModelStage

metadata:
  name: minimax-m3-mxfp8-gb300

cluster:
  id: nkx-slinky-gb300-dev-01

model:
  source:
    type: huggingface
    repository: MiniMaxAI/MiniMax-M3-MXFP8
    revision: c5454eb03678d8710e54a4e0fc681b9f3b4a3dba
  shared:
    root: /scratch/fsw/users/oleizerov/models
  local:
    root: /scratch/models

targets:
  gpuNodes: ALL

transfer:
  concurrency: 4
  allTargetsAllocation: true

verification:
  requireAllTargets: true
  minimumFreeSpace: 1Ti
